import sqlite3
connection = sqlite3.connect('conferences.db')
cursor = connection.cursor()
cursor.execute("""CREATE TABLE IF NOT EXISTS Users (id INTEGER PRIMARY KEY,l_image TEXT NOT NULL)""")
cursor.execute('INSERT INTO Users (id, l_image) VALUES (?, ?)', ('124', 'newuser@example.com'))
connection.commit()
cursor.execute('SELECT * FROM Users')
users = cursor.fetchall()
print(users)
connection.close()